pipeline {

    agent any

    environment {

        AWS_REGION = 'us-east-1'
        EKS_CLUSTER = 'devops-cluster'
        ECR_REGISTRY = '217428065218.dkr.ecr.us-east-1.amazonaws.com'
        ECR_REPO = 'python-app'

       
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/merong-ui/devops-project.git'
            }
        }

        // Git commit used as image version (best practice)
        IMAGE_TAG = "${GIT_COMMIT}"

        // Running unit tests in a Docker container ensures that the tests are executed in a consistent environment, regardless of where the Jenkins agent is running. This helps to avoid issues related to differences in local development environments and ensures that the tests are run with the same dependencies and configurations as the production environment.
        stage('Unit Test') {
            agent {
                docker {
                    image 'python:3.11-slim'
                }
        }
            // Installing dependencies and running unit tests in the same stage ensures that we are testing the exact code that will be analyzed by SonarQube in the next stage. This provides a more accurate assessment of code quality and helps to catch issues early in the pipeline before they are deployed to production.
            steps {
                sh '''
                    pip install --no-cache-dir -r app/requirements.txt
                    python -m unittest discover
                '''
            }
        }

        // Building the Docker image after successful tests ensures that only verified code is packaged and deployed.
        stage('Build Docker Image') {
            steps {
                sh """
                echo "Building Docker image"

                docker build -t $ECR_REPO:$IMAGE_TAG ./app

                docker tag $ECR_REPO:$IMAGE_TAG \
                $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                """
            }
        }

        stage('Login to ECR') {

            steps {
                sh """
                echo "Logging into ECR"

                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REGISTRY
                    """
            }
        }

        stage('Push Image to ECR') {
            steps {
                sh """
                echo "Pushing image"

                docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                """
            }
        }
    
        stage('Deploy to EKS') {

            steps {
                sh """
                echo "Updating kubeconfig"

                aws eks update-kubeconfig \
                    --region $AWS_REGION \
                    --name $EKS_CLUSTER

                echo "Checking cluster"

                kubectl get nodes

                echo "Deploying new image"

                kubectl set image deployment/python-app \
                python-app=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                """
            }
        }

        stage('Verify Deployment') {

            steps {

                sh '''
                    # Verifying the deployment by checking the rollout status of the deployment. This command will wait until the deployment is successfully rolled out, ensuring that the new image is running without issues.
                    kubectl rollout status deployment/python-app
                '''
            }
        }
    }


post {
        success {
            echo "Deployment SUCCESS"
        }
        failure {
            echo "Deployment FAILED"
        }

        // The always block ensures that the workspace is cleaned up after the pipeline execution, regardless of whether it succeeded or failed. This helps to maintain a clean environment for subsequent builds and prevents issues related to leftover files from previous runs.
        always {
            cleanWs()
        
        // The always block also includes a command to prune unused Docker images, which helps to free up disk space on the Jenkins agent. This is particularly important in CI/CD pipelines that build and push Docker images, as it prevents the accumulation of old and unused images that can consume significant storage over time.
            sh '''
                docker image prune -f || true
            '''
        }
      }
}

