pipeline {

    agent any

    environment {

        AWS_REGION = 'us-east-1'
        EKS_CLUSTER = 'prod-cluster'

        ECR_REGISTRY = '217428065218.dkr.ecr.us-east-1.amazonaws.com'
        ECR_REPO = 'python-application'

        // Git commit used as image version (best practice)
        IMAGE_TAG = "${GIT_COMMIT}"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/merong-ui/devops-project.git'
            }
        }

        stage('Build App') {
            steps {
                echo "Building application..."
            }
        }

        stage('Build Docker Image') {
            steps {
                sh """
                echo "Building Docker image"

                docker build -t $ECR_REPO:$IMAGE_TAG .

                docker tag $ECR_REPO:$IMAGE_TAG \
                $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                """
            }
        }

        stage('Push to ECR') {
            steps {
            environment {
                AWS_ACCESS_KEY_ID = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }
            {

                sh """
                echo "Logging into ECR"

                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REGISTRY

                echo "Pushing image"

                docker push $ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG
                """
            }
        }
    }
        stage('Deploy to EKS') {

            environment {
                AWS_ACCESS_KEY_ID = credentials('aws-access-key')
                AWS_SECRET_ACCESS_KEY = credentials('aws-secret-key')
            }

            steps {
                sh """
                echo "Updating kubeconfig"

                aws eks update-kubeconfig \
                    --region $AWS_REGION \
                    --name $EKS_CLUSTER

                echo "Checking cluster"

                kubectl get nodes

                echo "Deploying new image"

                kubectl set image deployment/myapp-deployment \
                python-application=$ECR_REGISTRY/$ECR_REPO:$IMAGE_TAG

                kubectl rollout status deployment/myapp-deployment
                """
            }
        }
    }
}
post {
        success {
            echo "Deployment SUCCESS"
        }
        failure {
            echo "Deployment FAILED"
        }
    }
}